shop/api/urls.py
__author__ = 'buremba'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^product/([0-9]+)/similar$', 'shop.api.views.product.similar', name="shop_api_product_similar"),
                       url(r'^product/([0-9]+)/vehicles', 'shop.api.views.product.vehicles', name="shop_api_product_vehicles"),
                       url(r'^product/([0-9]+)/information', 'shop.api.views.product.information', name="shop_api_product_information"),
                       url(r'^product/([0-9]+)/oem', 'shop.api.views.product.oem', name="shop_api_product_oem"),
                       url(r'^search/product_code', 'shop.api.views.product.search_product_code', name="shop_api_search_product_code"),
                       url(r'^search/manufacturer', 'shop.api.views.product.search_manufacturer', name="shop_api_search_manufacturer"),
                       url(r'^search/oem_code', 'shop.api.views.product.search_oem_code', name="shop_api_search_oem_code"),
                       url(r'^quicksearch', 'shop.api.views.product.product_quick_search', name="shop_api_quick_search"),
                       url(r'^search/product', 'shop.api.views.product.product_search', name="shop_api_search_product"),
                       url(r'^search/vehicle_tree', 'shop.api.views.product.search_vehicle_tree', name="shop_api_search_vehicle_tree"),
                       url(r'^search/category', 'shop.api.views.product.search_category', name="shop_api_search_vehicle_category"),
                       url(r'^city/?', 'shop.api.views.location.city', name="shop_api_city"),
                       url(r'^ilce/?', 'shop.api.views.location.ilce', name="shop_api_ilce"),
                       url(r'^category', 'shop.api.views.product.category_search', name="shop_api_product_category_search"),
                       url(r'^vehicle/tree', 'shop.api.views.vehicles.vehicle_path', name="shop_api_vehicle_tree"),
                       url(r'^vehicle/motor', 'shop.api.views.vehicles.motor_type', name="shop_api_vehicle_motor"),
                       url(r'^order/agreement', 'shop.api.views.order.satis_sozlesmesi', name="shop_api_order_satis_sozlesmesi"),
                       url(r'^vehicle/fuel', 'shop.api.views.vehicles.fuel_type', name="shop_api_vehicle_fuel"),
                       url(r'^vehicle/years', 'shop.api.views.vehicles.vehicle_years', name="shop_api_vehicle_years"),
                       url(r'^vehicle/product_support', 'shop.api.views.vehicles.product_supports_vehicle', name="shop_api_vehicle_product_support"),
)

shop/payment/urls.py
__author__ = 'buremba'

from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
                       url(r'^est/', include('shop.payment.est.urls')),
)

shop/urls.py
__author__ = 'buremba'
from django.views.generic import TemplateView

from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
                       url(r'^$', 'shop.views.homepage', name="shop_homepage"),
                       url(r'^list/?$', 'shop.views.search_page', name="shop_list_page"),
                       url(r'^account/', include('shop.customer.urls')),
                       url(r'^p/(.+)$', 'shop.views.page', name="shop_page"),
                       url(r'^t/(.+)$', 'shop.views.tag_page', name="shop_tag_page"),
                       url(r'^c/(.+)$', 'shop.views.category', name="shop_category_page"),
                       url(
                           r'^v/(?P<vehicle_tree>[a-zA-Z0-9_-]+)/?(?:/(?P<motor>[a-zA-Z0-9_-]+))?(?:/(?P<fuel>[a-zA-Z0-9_-]+))?$',
                           'shop.views.vehicle_page', name="shop_vehicle_page"),
                       url(r'(.+)/(.+)-([0-9]+)$', 'shop.views.product_page', name="shop_product"),
                       url(r'^payment/', include('shop.payment.urls')),
                       url(r'^api/', include('shop.api.urls')),
                       url(r'^kullanim-sozlesmesi$', 'shop.views.tos_page', name="shop_page_tos"),
                       url(r'^hakkimizda$', 'shop.views.about_us', name="shop_page_about_us"),
                       url(r'^iletisim', 'shop.views.contact_us', name="shop_page_contact_us"),
                       url(r'^anlasmali-sirketler', 'shop.views.affiliates', name="shop_page_affiliates"),
                       url(r'^module/pricedropalert/', include('shop.modules.pricedropalert.urls')),
                       url(r'^module/stockalert/', include('shop.modules.stockalert.urls')),
                       url(r'^ajax/main_menu/$', 'shop.views.main_menu_ajax', name='shop_ajax_main_menu'),
                       url(r'^module/messaging/', include('shop.modules.messaging.urls')),
                       url(r'^robots.txt$', TemplateView.as_view(template_name="shop/robots.txt", content_type= 'text/plain')),
)


def register(_url):
    urlpatterns.append(_url)

urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.decorators.cache import cache_page
from shop.sitemap import sitemaps
from django.contrib.sitemaps import views as sitemap_views

admin.autodiscover()

urlpatterns = patterns('',
       url(r'^', include("shop.urls", app_name='shop')),
       url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
       (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
       url(r'^sitemap\.xml$', cache_page(86400)(sitemap_views.index), {'sitemaps': sitemaps, 'sitemap_url_name': 'sitemaps'}),
       url(r'^sitemap-(?P<section>.+)\.xml.gz$', cache_page(86400)(sitemap_views.sitemap), {'sitemaps': sitemaps}, name='sitemaps'),
       url(r'^doc/', include('django.contrib.admindocs.urls'), name="admin_docs"),
       url(r'^tinymce/', include('tinymce.urls')),
       url(r'^administratorPage/filebrowser/', include("filebrowser.urls")),
       url(r'^admin_tools/', include("admin_tools.urls"), name="django_admin_tools_url"),
       url(r'^administratorPage/', include(admin.site.urls), name="django_admin_url"),
)

handler404 = 'shop.views.handler404'
handler500 = 'shop.views.handler500'
handler403 = 'shop.views.handler403'
handler400 = 'shop.views.handler400'

shop/customer/forms.py
# coding: utf-8
from captcha.fields import ReCaptchaField
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.models import get_current_site
from django.forms.util import ErrorList
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import ugettext_lazy as _
from shop.customer.models import CustomerAddress
from shop.models import City, Ilce


class LoginForm(forms.Form):
    email = forms.CharField(max_length=100, label=_(u'Email'))
    password = forms.CharField(widget=forms.PasswordInput(), label=_(u'Password'))
    remember_me = forms.BooleanField(required=False, label=_(u'Remember me'))

    def __init__(self, *args, **kwargs):
        captcha = kwargs.pop('captcha', False)
        super(LoginForm, self).__init__(*args, **kwargs)
        if captcha:
            self.fields['captcha'] = ReCaptchaField()


INVOICE_TYPE_CHOICES = (('personal', _('personal')), ('company', _('company')))


class CustomerAddressForm(forms.ModelForm):
    invoice_type = forms.ChoiceField(label=_('invoice type'), widget=forms.RadioSelect, choices=INVOICE_TYPE_CHOICES,
                                     initial='personal')
    city = forms.ModelChoiceField(label=_('city'), queryset=City.objects.filter(country_id=1))

    class Meta:
        fields = (
            'address_name', 'first_name', 'last_name', 'address', 'postcode', 'land_line', 'cell_phone', 'city',
            'invoice_type', 'identity_number', 'tax_authority', 'tax_no')
        model = CustomerAddress

    def __init__(self, *args, **kwargs):
        super(CustomerAddressForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = [
            'address_name', 'first_name', 'last_name', 'address', 'postcode', 'land_line', 'cell_phone',
            'city', 'invoice_type', 'identity_number', 'tax_authority', 'tax_no']

        if kwargs.get('instance'):
            if len(args) > 0 and args[0].get('city'):
                city_id = args[0].get('city')
                self.fields['ilce'] = forms.ModelChoiceField(label=_('ilçe'), queryset=Ilce.objects.filter(city_id=city_id),
                                                             initial=kwargs.get('instance').ilce_id)
            elif kwargs.get('instance').ilce is not None:
                ilce = kwargs.get('instance').ilce
                self.fields['ilce'] = forms.ModelChoiceField(queryset=Ilce.objects.filter(city_id=ilce.city_id),
                                                             initial=ilce)
                self.fields['city'].initial = ilce.city_id
            if "ilce" in self.fields:
                self.fields.keyOrder = [
                'address_name', 'first_name', 'last_name', 'address', 'postcode', 'land_line', 'cell_phone',
                'city', 'ilce', 'invoice_type', 'identity_number', 'tax_authority', 'tax_no']

    class Media:
        js = ('customer/js/modify_address.js',)

    def clean(self):
        invoice_type = self.cleaned_data.get('invoice_type')
        if invoice_type == 'personal':
            if not self.cleaned_data.get('identity_number'):
                self._errors["identity_number"] = self.error_class([_("This field is required.")])
            self.cleaned_data['invoice_type'] = None
            self.cleaned_data['tax_no'] = None
        elif invoice_type == 'company':
            if not self.cleaned_data.get('tax_no'):
                self._errors["tax_no"] = self.error_class([_("This field is required.")])
            if not self.cleaned_data.get('tax_authority'):
                self._errors["tax_authority"] = self.error_class([_("This field is required.")])
            self.cleaned_data['identity_number'] = None
        data = super(CustomerAddressForm, self).clean()
        return data

    def save(self, force_insert=False, force_update=False, commit=True):
        if self.data.get('ilce') is not None:
            self.instance.ilce_id = int(self.data.get('ilce'))
        return super(CustomerAddressForm, self).save(commit)


class RegisterForm(forms.Form):
    email = forms.EmailField(label=_(u'Email'))
    password1 = forms.CharField(widget=forms.PasswordInput(), label=_(u'Password'), min_length=5)
    password2 = forms.CharField(widget=forms.PasswordInput(), label=_(u'Password *(Again)'))
    first_name = forms.CharField(label=_(u'First name'))
    last_name = forms.CharField(label=_(u'Last name'), required=False)
    phone = forms.CharField(label=_(u'Phone number'), required=False)
    agreement = forms.BooleanField(required=True)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if not password2:
            raise forms.ValidationError("Şifrenizi teyit etmemiz için iki kere girmeniz gerekiyor.")
        if password1 != password2:
            raise forms.ValidationError("Şifreleriniz eşleşmiyor")
        return password2


class ProfileUpdateForm(forms.Form):
    email = forms.EmailField(label=_(u'Email'), required=False, )
    old_password = forms.CharField(widget=forms.PasswordInput(), label=_(u'Old Password'), required=False)
    new_password = forms.CharField(widget=forms.PasswordInput(), label=_(u'New password'), required=False)
    first_name = forms.CharField(label=_(u'First name'))
    last_name = forms.CharField(label=_(u'Last name'), required=False)
    phone = forms.CharField(label=_(u'Phone number'), required=False)

    def __init__(self, user, data=None, files=None, auto_id='id_%s', prefix=None,
                 initial=None, error_class=ErrorList, label_suffix=None,
                 empty_permitted=False):
        if data:
            data = data.copy()
            data['email'] = user.email
        else:
            initial = {"email": user.email, "first_name": user.first_name, "last_name": user.last_name,
                       "phone": user.phone}
        super(ProfileUpdateForm, self).__init__(data, files, auto_id, prefix,
                                                initial, error_class, label_suffix,
                                                empty_permitted)
        self.user = user
        self.fields['email'].widget.attrs['disabled'] = 'disabled'

    def clean(self):
        cleaned_data = super(ProfileUpdateForm, self).clean()
        if "new_password" in cleaned_data and not cleaned_data.get("old_password"):
            raise forms.ValidationError(_("You need to enter your old password in order to update your password"))
        return cleaned_data

    def clean_old_password(self):
        old_pass = self.cleaned_data.get('old_password')
        if old_pass and not self.user.check_password(old_pass):
            raise forms.ValidationError(_("The password you entered is wrong."))
        return old_pass

    def save(self):
        customer = self.user
        customer.email = self.cleaned_data['email']
        customer.first_name = self.cleaned_data['first_name']
        customer.last_name = self.cleaned_data['last_name']
        customer.phone = self.cleaned_data['phone']
        if self.cleaned_data.get('new_password'):
            customer.set_password(self.cleaned_data.get('new_password'))
        customer.save()


class PasswordResetForm(forms.Form):
    email = forms.EmailField(label=_("Email"), max_length=254)

    def __init__(self, *args, **kwargs):
        captcha = kwargs.pop('captcha', False)
        super(PasswordResetForm, self).__init__(*args, **kwargs)
        if captcha:
            self.fields['captcha'] = ReCaptchaField()


    def set_captcha(self):
        self.fields['captcha'] = ReCaptchaField()

    def save(self, domain_override=None,
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None):
        """
        Generates a one-use only link for resetting password and sends to the
        user.
        """
        from django.core.mail import send_mail

        email = self.cleaned_data["email"]
        active_users = get_user_model()._default_manager.filter(
            email__iexact=email, is_active=True)
        for user in active_users:
            # Make sure that no email is sent to a user that actually has
            # a password marked as unusable
            if not user.has_usable_password():
                continue
            if not domain_override:
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override
            c = {
                'email': user.email,
                'domain': domain,
                'site_name': site_name,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': 'https' if use_https else 'http',
            }
            subject = loader.render_to_string(subject_template_name, c)
            # Email subject *must not* contain newlines
            subject = ''.join(subject.splitlines())
            email = loader.render_to_string(email_template_name, c)
            send_mail(subject, email, from_email, [user.email])

shop/importer/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class UploadForm(forms.Form):
    file = forms.FileField(label=_(u'file'))

shop/modules/messaging/forms.py
from django import forms
from django.utils.translation import ugettext as _
from shop.customer.models import Order
from shop.modules.messaging.models import MessageDepartment


class NewCustomerMessage(forms.Form):
    message = forms.CharField(widget=forms.Textarea(), label=_(u'message'), required=True)


class CustomerMessageForm(forms.Form):
    topic = forms.CharField(max_length=100, label=_(u'topic'))
    order = forms.ModelChoiceField(queryset=None, label=_(u'order'), required=False)
    department = forms.ModelChoiceField(MessageDepartment.objects.all(), label=_(u'department'), required=True)
    message = forms.CharField(widget=forms.Textarea(), label=_(u'message'))

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(CustomerMessageForm, self).__init__(*args, **kwargs)

        self.fields['order'].queryset = Order.objects.filter(customer=user)

shop/api/views/location.py
import json
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from shop.models import City, Ilce


@csrf_exempt
def city(request):
    try:
        country = int(request.POST.get('country'))
    except:
        return HttpResponse(json.dumps({"error": "country is required"}), content_type="application/json")

    cities = City.objects.filter(country_id=country)
    return HttpResponse(json.dumps(list(cities.values())), content_type="application/json")


@csrf_exempt
def ilce(request):
    try:
        city = int(request.POST.get('city'))
    except:
        return HttpResponse(json.dumps({"error": "city is required"}), content_type="application/json")

    ilceler = Ilce.objects.filter(city_id=city)
    return HttpResponse(json.dumps(list(ilceler.values())), content_type="application/json")

shop/templates/shop/default/about_us.html
{% extends "shop/"|add:SHOP_TEMPLATE|add:"/base.html" %}
{% load simit_tags %}


{% block content %}
    <div class="wrapper">
        <h1>Hakkımızda</h1>
        <div>{% variable "ABOUT_US" "Hakkımızda" "RICH_TEXT" "Hakkımızda" "Hakkımızda sayfasının içeriği" %}</div>
    </div>
{% endblock %}

shop/templates/shop/default/affiliates.html
{% extends "shop/"|add:SHOP_TEMPLATE|add:"/base.html" %}
{% load simit_tags %}


{% block content %}
    <div class="wrapper">
        <h1>Anlaşmalı Şirketler</h1>
        <div>{% variable "AFFILIATES" "Anlaşmalı Şirketler" "RICH_TEXT" "Anlaşmalı Şirketler" "Sitedeki ürünlerin kaynakları" %}</div>
    </div>
{% endblock %}

shop/templates/shop/default/contact_us.html
{% extends "shop/"|add:SHOP_TEMPLATE|add:"/base.html" %}
{% load simit_tags %}


{% block content %}
    <div class="wrapper">
        <h1>İletişim</h1>
        <div>{% variable "CONTACT_US" "İletişim" "RICH_TEXT" "İletişim" "İletişim sayfasının içeriği" %}</div>
    </div>
{% endblock %}

shop/templates/shop/default/login.html
{% extends "shop/"|add:SHOP_TEMPLATE|add:"/base.html" %}

{% block content %}
    <div class="wrapper">
        <div class="loginSection">
            <div class="LoginHead clearfix">
                <h1>Üye Girişi</h1>
            </div>
            <div class="LoginCon">
                <form action="" method="post" {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>{% csrf_token %}
                    {% for error in form.non_field_errors %}
                        {{ error }}
                    {% endfor %}
                    {% for field in form %}
                        <div class="fieldWrapper {{ field.id_for_label }}_container">
                            {{ field.errors }}
                            {{ field.label_tag }} {{ field }}
                        </div>
                    {% endfor %}
                    <div><a href="{% url "password_reset" %}">Şifremi Unuttum</a></div>
                    <input class="button_blue1 button_size3" type="submit" id="L-Enter" value="Giriş Yap" tabindex="4" name="pass" alt="Giriş Yap" title="Giriş Yap">
                </form>
            </div>
        </div>
                <a href="{% url "shop_customer_register" %}" class="sign-up-btn button_blue1 button_size3">Üye Değil Misin? <span>30 saniyede kayıt ol</span></a>

    </div>
{% endblock %}

shop/templates/shop/default/page.html
{% extends "shop/"|add:SHOP_TEMPLATE|add:"/base.html" %}

{% block header %}
    {{ block.super }}
    {% if page.tags %}
        <meta name="keywords" content="{{ page.tags }}">{% endif %}
    {% if page.description %}
        <meta name="description" content="{{ page.description }}"> {% endif %}
{% endblock %}

{% block title %}
    {% if page.title %} {{ page.title }} {% else %} {{ page.name }} {% endif %}
{% endblock %}

{% block content %}
    <div class="wrapper">
        <h1>{{ page.name }}</h1>
        <p>{{ page.content|safe }}</p>
    </div>
{% endblock %}

shop/templates/shop/default/register.html
{% extends "shop/"|add:SHOP_TEMPLATE|add:"/base.html" %}

{% block content %}
    <div class="wrapper">
        <div class="loginSection">
            <div class="LoginHead clearfix">
                <h1>Üye Ol</h1>
            </div>
            <div class="LoginCon">
                <form action="" method="post" {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>{% csrf_token %}
                    {% for field in form %}
                        {% if field.name != "agreement" %}
                        <div class="fieldWrapper">
                            {{ field.errors }}
                            {% if field.field.required %}<b>{{ field.label_tag }}</b>{% else %}{{ field.label_tag }}{% endif %} {{ field }}
                        </div>
                        {% endif %}
                    {% endfor %}
                    <div class="fieldWrapper">{{ form.agreement.errors }}<input type="checkbox" id="id_agreement" name="agreement"><a href="javascript:void(0)" onclick='box({source: $("#tos").html(), modal: true, width:600, title:"Kullanıcı Sözleşmesi"});' id="open_agreement" style="display: inline-block; font-weight: normal">kullanıcı sözleşmesini kabul ediyorum.</a></div>
                    <input class="button_blue1 button_size3" type="submit" id="L-Enter" value="Kayıt ol" tabindex="4" name="pass" alt="Kayıt ol" title="Kayıt ol">
                </form>
            </div>
        </div>
    </div>
    <div style="display: none" id="tos">
        {{ agreement|safe }}
    </div>
    <script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 967879405;
    var google_conversion_language = "tr";
    var google_conversion_format = "3";
    var google_conversion_color = "ffffff";
    var google_conversion_label = "trdPCNPmrQgQ7dXCzQM";
    var google_remarketing_only = false;
    /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
    </script>
    <noscript>
    <div style="display:inline;">
    <img height="1" width="1" style="border-style:none;" alt="" src="//www.googleadservices.com/pagead/conversion/967879405/?label=trdPCNPmrQgQ7dXCzQM&amp;guid=ON&amp;script=0"/>
    </div>
    </noscript>

{% endblock %}

shop/templates/shop/default/tos_page.html
{% extends "shop/"|add:SHOP_TEMPLATE|add:"/base.html" %}
{% load simit_tags %}


{% block content %}
    <div class="wrapper">
        <h1>Kullanım Sözleşmesi</h1>
        <div>{% variable "TOS" "Kullanım Sözleşmesi" "RICH_TEXT" "Kullanım Sözleşmesi" "Site kullanıcılarının alışveriş yapabilmeleri için imzalamaları gereken sözleşme" %}</div>
    </div>
{% endblock %}