shop/api/urls.py
__author__ = 'buremba'

from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^product/([0-9]+)/similar$', 'shop.api.views.product.similar', name="shop_api_product_similar"),
                       url(r'^product/([0-9]+)/vehicles', 'shop.api.views.product.vehicles', name="shop_api_product_vehicles"),
                       url(r'^product/([0-9]+)/information', 'shop.api.views.product.information', name="shop_api_product_information"),
                       url(r'^product/([0-9]+)/oem', 'shop.api.views.product.oem', name="shop_api_product_oem"),
                       url(r'^search/product_code', 'shop.api.views.product.search_product_code', name="shop_api_search_product_code"),
                       url(r'^search/manufacturer', 'shop.api.views.product.search_manufacturer', name="shop_api_search_manufacturer"),
                       url(r'^search/oem_code', 'shop.api.views.product.search_oem_code', name="shop_api_search_oem_code"),
                       url(r'^quicksearch', 'shop.api.views.product.product_quick_search', name="shop_api_quick_search"),
                       url(r'^search/product', 'shop.api.views.product.product_search', name="shop_api_search_product"),
                       url(r'^search/vehicle_tree', 'shop.api.views.product.search_vehicle_tree', name="shop_api_search_vehicle_tree"),
                       url(r'^search/category', 'shop.api.views.product.search_category', name="shop_api_search_vehicle_category"),
                       url(r'^city/?', 'shop.api.views.location.city', name="shop_api_city"),
                       url(r'^ilce/?', 'shop.api.views.location.ilce', name="shop_api_ilce"),
                       url(r'^category', 'shop.api.views.product.category_search', name="shop_api_product_category_search"),
                       url(r'^vehicle/tree', 'shop.api.views.vehicles.vehicle_path', name="shop_api_vehicle_tree"),
                       url(r'^vehicle/motor', 'shop.api.views.vehicles.motor_type', name="shop_api_vehicle_motor"),
                       url(r'^order/agreement', 'shop.api.views.order.satis_sozlesmesi', name="shop_api_order_satis_sozlesmesi"),
                       url(r'^vehicle/fuel', 'shop.api.views.vehicles.fuel_type', name="shop_api_vehicle_fuel"),
                       url(r'^vehicle/years', 'shop.api.views.vehicles.vehicle_years', name="shop_api_vehicle_years"),
                       url(r'^vehicle/product_support', 'shop.api.views.vehicles.product_supports_vehicle', name="shop_api_vehicle_product_support"),
)

shop/payment/urls.py
__author__ = 'buremba'

from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
                       url(r'^est/', include('shop.payment.est.urls')),
)

shop/urls.py
__author__ = 'buremba'
from django.views.generic import TemplateView

from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
                       url(r'^$', 'shop.views.homepage', name="shop_homepage"),
                       url(r'^list/?$', 'shop.views.search_page', name="shop_list_page"),
                       url(r'^account/', include('shop.customer.urls')),
                       url(r'^p/(.+)$', 'shop.views.page', name="shop_page"),
                       url(r'^t/(.+)$', 'shop.views.tag_page', name="shop_tag_page"),
                       url(r'^c/(.+)$', 'shop.views.category', name="shop_category_page"),
                       url(
                           r'^v/(?P<vehicle_tree>[a-zA-Z0-9_-]+)/?(?:/(?P<motor>[a-zA-Z0-9_-]+))?(?:/(?P<fuel>[a-zA-Z0-9_-]+))?$',
                           'shop.views.vehicle_page', name="shop_vehicle_page"),
                       url(r'(.+)/(.+)-([0-9]+)$', 'shop.views.product_page', name="shop_product"),
                       url(r'^payment/', include('shop.payment.urls')),
                       url(r'^api/', include('shop.api.urls')),
                       url(r'^kullanim-sozlesmesi$', 'shop.views.tos_page', name="shop_page_tos"),
                       url(r'^hakkimizda$', 'shop.views.about_us', name="shop_page_about_us"),
                       url(r'^iletisim', 'shop.views.contact_us', name="shop_page_contact_us"),
                       url(r'^anlasmali-sirketler', 'shop.views.affiliates', name="shop_page_affiliates"),
                       url(r'^module/pricedropalert/', include('shop.modules.pricedropalert.urls')),
                       url(r'^module/stockalert/', include('shop.modules.stockalert.urls')),
                       url(r'^ajax/main_menu/$', 'shop.views.main_menu_ajax', name='shop_ajax_main_menu'),
                       url(r'^module/messaging/', include('shop.modules.messaging.urls')),
                       url(r'^robots.txt$', TemplateView.as_view(template_name="shop/robots.txt", content_type= 'text/plain')),
)


def register(_url):
    urlpatterns.append(_url)

urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.decorators.cache import cache_page
from shop.sitemap import sitemaps
from django.contrib.sitemaps import views as sitemap_views

admin.autodiscover()

urlpatterns = patterns('',
       url(r'^', include("shop.urls", app_name='shop')),
       url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
       (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
       url(r'^sitemap\.xml$', cache_page(86400)(sitemap_views.index), {'sitemaps': sitemaps, 'sitemap_url_name': 'sitemaps'}),
       url(r'^sitemap-(?P<section>.+)\.xml.gz$', cache_page(86400)(sitemap_views.sitemap), {'sitemaps': sitemaps}, name='sitemaps'),
       url(r'^doc/', include('django.contrib.admindocs.urls'), name="admin_docs"),
       url(r'^tinymce/', include('tinymce.urls')),
       url(r'^administratorPage/filebrowser/', include("filebrowser.urls")),
       url(r'^admin_tools/', include("admin_tools.urls"), name="django_admin_tools_url"),
       url(r'^administratorPage/', include(admin.site.urls), name="django_admin_url"),
)

handler404 = 'shop.views.handler404'
handler500 = 'shop.views.handler500'
handler403 = 'shop.views.handler403'
handler400 = 'shop.views.handler400'

shop/modules/pricedropalert/models.py
# coding: utf-8

from django.db import models
from shop.models import Product, User
from django.utils.translation import ugettext as _
from shop.newsletter.models import MAILS

MAILS['price_drop_alert_customer'] = {'customer': 'Kullanıcı öğesi', 'product': 'Ürün', 'product_url': ''}


class PriceDropAlertEmail(models.Model):
    email = models.EmailField(_('email'))
    product = models.ForeignKey(Product, related_name="pricedrop_email")
    checkpoint_price = models.DecimalField(_('checkpoint price'), decimal_places=2, max_digits=17)
    saved_time = models.DateTimeField(auto_created=True, auto_now=True)

    class Meta:
        db_table = 'module_pricedropalert_email'
        verbose_name = 'Price Drop Alert Email List'
        unique_together = ('email', 'product')


class PriceDropAlertCustomer(models.Model):
    customer = models.ForeignKey(User)
    product = models.ForeignKey(Product, related_name="pricedrop_customer")
    checkpoint_price = models.DecimalField(_('checkpoint price'), decimal_places=2, max_digits=17)
    saved_time = models.DateTimeField(auto_created=True, auto_now=True)


    class Meta:
        db_table = 'module_pricedropalert_customer'
        verbose_name = 'Price Drop Alert Customer List'
        unique_together = ('customer', 'product')

shop/customer/forms.py
# coding: utf-8
from captcha.fields import ReCaptchaField
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.models import get_current_site
from django.forms.util import ErrorList
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import ugettext_lazy as _
from shop.customer.models import CustomerAddress
from shop.models import City, Ilce


class LoginForm(forms.Form):
    email = forms.CharField(max_length=100, label=_(u'Email'))
    password = forms.CharField(widget=forms.PasswordInput(), label=_(u'Password'))
    remember_me = forms.BooleanField(required=False, label=_(u'Remember me'))

    def __init__(self, *args, **kwargs):
        captcha = kwargs.pop('captcha', False)
        super(LoginForm, self).__init__(*args, **kwargs)
        if captcha:
            self.fields['captcha'] = ReCaptchaField()


INVOICE_TYPE_CHOICES = (('personal', _('personal')), ('company', _('company')))


class CustomerAddressForm(forms.ModelForm):
    invoice_type = forms.ChoiceField(label=_('invoice type'), widget=forms.RadioSelect, choices=INVOICE_TYPE_CHOICES,
                                     initial='personal')
    city = forms.ModelChoiceField(label=_('city'), queryset=City.objects.filter(country_id=1))

    class Meta:
        fields = (
            'address_name', 'first_name', 'last_name', 'address', 'postcode', 'land_line', 'cell_phone', 'city',
            'invoice_type', 'identity_number', 'tax_authority', 'tax_no')
        model = CustomerAddress

    def __init__(self, *args, **kwargs):
        super(CustomerAddressForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = [
            'address_name', 'first_name', 'last_name', 'address', 'postcode', 'land_line', 'cell_phone',
            'city', 'invoice_type', 'identity_number', 'tax_authority', 'tax_no']

        if kwargs.get('instance'):
            if len(args) > 0 and args[0].get('city'):
                city_id = args[0].get('city')
                self.fields['ilce'] = forms.ModelChoiceField(label=_('ilçe'), queryset=Ilce.objects.filter(city_id=city_id),
                                                             initial=kwargs.get('instance').ilce_id)
            elif kwargs.get('instance').ilce is not None:
                ilce = kwargs.get('instance').ilce
                self.fields['ilce'] = forms.ModelChoiceField(queryset=Ilce.objects.filter(city_id=ilce.city_id),
                                                             initial=ilce)
                self.fields['city'].initial = ilce.city_id
            if "ilce" in self.fields:
                self.fields.keyOrder = [
                'address_name', 'first_name', 'last_name', 'address', 'postcode', 'land_line', 'cell_phone',
                'city', 'ilce', 'invoice_type', 'identity_number', 'tax_authority', 'tax_no']

    class Media:
        js = ('customer/js/modify_address.js',)

    def clean(self):
        invoice_type = self.cleaned_data.get('invoice_type')
        if invoice_type == 'personal':
            if not self.cleaned_data.get('identity_number'):
                self._errors["identity_number"] = self.error_class([_("This field is required.")])
            self.cleaned_data['invoice_type'] = None
            self.cleaned_data['tax_no'] = None
        elif invoice_type == 'company':
            if not self.cleaned_data.get('tax_no'):
                self._errors["tax_no"] = self.error_class([_("This field is required.")])
            if not self.cleaned_data.get('tax_authority'):
                self._errors["tax_authority"] = self.error_class([_("This field is required.")])
            self.cleaned_data['identity_number'] = None
        data = super(CustomerAddressForm, self).clean()
        return data

    def save(self, force_insert=False, force_update=False, commit=True):
        if self.data.get('ilce') is not None:
            self.instance.ilce_id = int(self.data.get('ilce'))
        return super(CustomerAddressForm, self).save(commit)


class RegisterForm(forms.Form):
    email = forms.EmailField(label=_(u'Email'))
    password1 = forms.CharField(widget=forms.PasswordInput(), label=_(u'Password'), min_length=5)
    password2 = forms.CharField(widget=forms.PasswordInput(), label=_(u'Password *(Again)'))
    first_name = forms.CharField(label=_(u'First name'))
    last_name = forms.CharField(label=_(u'Last name'), required=False)
    phone = forms.CharField(label=_(u'Phone number'), required=False)
    agreement = forms.BooleanField(required=True)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if not password2:
            raise forms.ValidationError("Şifrenizi teyit etmemiz için iki kere girmeniz gerekiyor.")
        if password1 != password2:
            raise forms.ValidationError("Şifreleriniz eşleşmiyor")
        return password2


class ProfileUpdateForm(forms.Form):
    email = forms.EmailField(label=_(u'Email'), required=False, )
    old_password = forms.CharField(widget=forms.PasswordInput(), label=_(u'Old Password'), required=False)
    new_password = forms.CharField(widget=forms.PasswordInput(), label=_(u'New password'), required=False)
    first_name = forms.CharField(label=_(u'First name'))
    last_name = forms.CharField(label=_(u'Last name'), required=False)
    phone = forms.CharField(label=_(u'Phone number'), required=False)

    def __init__(self, user, data=None, files=None, auto_id='id_%s', prefix=None,
                 initial=None, error_class=ErrorList, label_suffix=None,
                 empty_permitted=False):
        if data:
            data = data.copy()
            data['email'] = user.email
        else:
            initial = {"email": user.email, "first_name": user.first_name, "last_name": user.last_name,
                       "phone": user.phone}
        super(ProfileUpdateForm, self).__init__(data, files, auto_id, prefix,
                                                initial, error_class, label_suffix,
                                                empty_permitted)
        self.user = user
        self.fields['email'].widget.attrs['disabled'] = 'disabled'

    def clean(self):
        cleaned_data = super(ProfileUpdateForm, self).clean()
        if "new_password" in cleaned_data and not cleaned_data.get("old_password"):
            raise forms.ValidationError(_("You need to enter your old password in order to update your password"))
        return cleaned_data

    def clean_old_password(self):
        old_pass = self.cleaned_data.get('old_password')
        if old_pass and not self.user.check_password(old_pass):
            raise forms.ValidationError(_("The password you entered is wrong."))
        return old_pass

    def save(self):
        customer = self.user
        customer.email = self.cleaned_data['email']
        customer.first_name = self.cleaned_data['first_name']
        customer.last_name = self.cleaned_data['last_name']
        customer.phone = self.cleaned_data['phone']
        if self.cleaned_data.get('new_password'):
            customer.set_password(self.cleaned_data.get('new_password'))
        customer.save()


class PasswordResetForm(forms.Form):
    email = forms.EmailField(label=_("Email"), max_length=254)

    def __init__(self, *args, **kwargs):
        captcha = kwargs.pop('captcha', False)
        super(PasswordResetForm, self).__init__(*args, **kwargs)
        if captcha:
            self.fields['captcha'] = ReCaptchaField()


    def set_captcha(self):
        self.fields['captcha'] = ReCaptchaField()

    def save(self, domain_override=None,
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None):
        """
        Generates a one-use only link for resetting password and sends to the
        user.
        """
        from django.core.mail import send_mail

        email = self.cleaned_data["email"]
        active_users = get_user_model()._default_manager.filter(
            email__iexact=email, is_active=True)
        for user in active_users:
            # Make sure that no email is sent to a user that actually has
            # a password marked as unusable
            if not user.has_usable_password():
                continue
            if not domain_override:
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override
            c = {
                'email': user.email,
                'domain': domain,
                'site_name': site_name,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': 'https' if use_https else 'http',
            }
            subject = loader.render_to_string(subject_template_name, c)
            # Email subject *must not* contain newlines
            subject = ''.join(subject.splitlines())
            email = loader.render_to_string(email_template_name, c)
            send_mail(subject, email, from_email, [user.email])

shop/importer/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class UploadForm(forms.Form):
    file = forms.FileField(label=_(u'file'))

shop/templates/shop/dega/includes/breadcrumb-table.html
{% load shop_tags %}
<tr class="breadcrumb">
    {% if render_homepage != False %}<li><span typeof="v:Breadcrumb"><a class="no" href="{% url 'shop_homepage' %}" rel="v:url" property="v:title" title="Anasayfa">Anasayfa</a></span></li>{% endif %}
    {% for item in items %}
        {% if forloop.counter == 1 or forloop.counter == 2 or forloop.counter == 6   %}
           <td><a href="{% if tag == "url" %}{% url property item.slug %}{% elif tag == "link" %}{{ item.url }}{% else %}{% change_parameter_url property item.slug %}{% endif %}" rel="v:url" property="v:title" title="yedek parça">{{ item.name }}</a></td>
        {% endif %}
    {% endfor %}
</tr>

shop/templates/shop/dega/includes/filters.html
{% load shop_tags %}

    <div class="category-filter filter-container">
        <h5>Kategoriler</h5>
        <ul class="filter-middle cat-anch-main margin-top-10px">
            {% if category %}
                {% recursetree category.cached_ancestors %}

                    <li>
                    {% if category.id == node.id %}
                        <a class="selected" rakam-event-attribute="category"
                           href="{% change_parameter_url "c" node.slug %}">
                            {{ node.name }}{% if result.facets.count %} <span>({{ result.facets.count }})</span>
                                <a class="close_button" href="{% remove_parameter_url "c" %}">x</a>
                            {% endif %}</a>
                    {% else %}
                        <a href="{% change_parameter_url "c" node.slug %}">{{ node.name }}</a>
                    {% endif %}
                    {% if not node.is_leaf_node %}
                        <ul class="filter-middle">
                            {{ children }}
                        </ul>
                    {% endif %}

                {% endrecursetree %}
            {% endif %}
            <ul class="filter-middle">
                {% for item in result.facets.category %}
                    {% if item.name != "-" %}
                        <li>
                        <a href="{% change_parameter_url "c" item.slug %}" title="{{ item.name }}">{{ item.name }}</a>
                        {% if show_count %}<span>({{ item.count }})</span>{% endif %}
                    {% endif %}
                {% endfor %}
            </ul>
            </li>
        </ul>
    </div>

{% if result.facets.vehicle or vlevel == 5 %}
    <div class="vehicle-filter filter-container">
        <h5>{% if vlevel == 0 %}Araç Modeli{% elif vlevel == 1 %}Araç Model
            Tipi{% elif vlevel >= 4 %}Araç
            Yılı{% else %}Araç Markası{% endif %}
            <a href="{% remove_parameter_url "v" %}" class="filter-close close_button">x</a>
        </h5>
        {#            {% if result.facets.vehicle|length > 10 %}#}
        {#                <input type="search" class="filter-input" data-notfound="Aramanızla eşleşen araç bulunamadı."#}
        {#                       data-target="vehicle_list" placeholder="Sayfa içi filtre">#}
        {#            {% endif %}#}
        <ul id="vehicle_list" class="filter-middle cat-anch-main margin-top-10px fixed-max-height">
            {% for item in vehiclepath %}
                {% if item.name != "-" %}
                    <li style="color:#d6282d">{{ item.name }} <a class="close_button"
                                                                 href="{% remove_parameter_url "v" %}">x</a></li>
                {% endif %}
            {% endfor %}
            {% if vehicle_year %}
                <li style="color:#d6282d">{{ vehicle_year.name }} <a class="close_button"
                                                                href="{% remove_parameter_url "vyear" %}">x</a></li>

            {% endif %}
            {% for item in result.facets.vehicle %}
                <li data="{{ item.name|lower }}"><a href="
                    {% if vlevel == 0 %}{% change_parameter_url 'v' item.slug %}{% elif vlevel == 4 %}{% change_parameter_url 'vyear' item.slug %}{% else %}{% change_parameter_url 'v' item.slug %}{% endif %}"
                                                    title="{{ item.name }}">{{ item.name }}
                {% if show_count and item.count %}
                    <span>({{ item.count }})</span>{% endif %}</a> <span></span>
            {% endfor %}
        </ul>
    </div>
{% endif %}

{% if result.facets.tag %}
    <div class="tag-filter filter-container">
        <h5>Etiket</h5>
        <ul class="filter-middle checkbox-styled-anchor fixed-max-height margin-top-10px">
            {% for tag in result.facets.tag %}
                <li><a {% param_exists "tag" tag.id %}class="checked"{% endparam_exists %}
                       href="{% toggle_parameter_url "tag" tag.id %}">{{ tag.name }}{% if tag.count %}<span>
                    ({{ tag.count }})</span>{% endif %}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

{% if result.facets.manufacturer and False %}
    <div class="manufacturer-filter filter-container">
        <h5>Marka</h5>
        {#            {% if result.facets.manufacturer|length > 10 %}#}
        {#                <input type="search" class="filter-input" data-notfound="Aramanızla eşleşen marka bulunamadı."#}
        {#                       data-target="manufacturer_list" placeholder="Sayfa içi filtre">#}
        {#            {% endif %}#}
        <ul id="manufacturer_list" class="filter-middle checkbox-styled-anchor fixed-max-height margin-top-10px">
            {% for manufacturer in result.facets.manufacturer %}
                <li data="{{ manufacturer.name|lower }}"><a
                        {% param_exists "br" manufacturer.id %}class="checked"{% endparam_exists %}
                        href="{% toggle_parameter_url "br" manufacturer.id %}">
                    {{ manufacturer.name }}{% if manufacturer.count %}
                        <span>({{ manufacturer.count }})</span>{% endif %}</a></li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

{% if categoryfields %}
    <div class="categoryyfields-filter filter-container">
        <a href="#" class="anchor-title sub-anchor-title sub-anchor-title-first-child">Ürün Özellikleri</a>
        <ul class="filter-middle checkbox-styled-anchor">
            {% for name, choices in categoryfields.items %}
                <li class="title">{{ name }}</li>
                {% for choice in choices %}
                    <li><a href="{% change_parameter_url name choice %}">{{ choice }}</a></li>
                {% endfor %}
            {% endfor %}
        </ul>
    </div>
{% endif %}

<h5>Fiyat Aralığı</h5>
<ul class="filter-middle price-filter filter-container">
    <form>
        {% for key, value in request.GET.items %}
            {% if key != "price0" and key != "price1" %}
                <input type="hidden" name="{{ key }}" value="{{ value }}">
            {% endif %}
        {% endfor %}
        <input name="price0" type="text" class="small-input number" placeholder="min TL"
               rakam-event-attribute="min_price"
               value="{{ request.GET.price0 }}"/>

        <div class="splitter">-</div>
        <input name="price1" type="text" class="small-input number" placeholder="max TL"
               rakam-event-attribute="max_price"
               value="{{ request.GET.price1 }}"/>
        <input type="submit" class="button_blue1 small-btn search-button" value="" style="top: 3px;position: relative;">
    </form>
</ul>

shop/templates/shop/dega/includes/login_modal.html
{% load i18n %}

<div class="LoginCon modal">
    <form action="{% url "shop_customer_login" %}" method="post">
{#    <form action="https://{{ request.get_host }}/{% url "shop_customer_login" %}" method="post">#}
        {% csrf_token %}
        <div class="fieldWrapper">
            <label for="id_email">Eposta:</label> <input id="id_email" maxlength="100"
                                                         name="email" type="text">
        </div>

        <div class="fieldWrapper">
            <label for="id_password">Şifre:</label> <input id="id_password" name="password"
                                                           type="password">
        </div>

        <div class="fieldWrapper">
            <label for="id_remember_me" style="display:inline">{% trans "Remember me" %}:</label> <input
                id="id_remember_me" name="remember_me" type="checkbox">
        </div>
        <div><a href="{% url "password_reset" %}">Şifremi Unuttum</a></div>
        <input class="button_blue1 right" type="submit" id="L-Enter" value="Giriş Yap"
               tabindex="4" name="pass" alt="Giriş Yap" title="Giriş Yap">
    </form>
</div>

shop/templates/shop/dega/includes/top_category_list.html
{% load shop_tags %}

<div class="block products_block panel panel-default">
            <h4 class="title_block panel-heading">
                <a >
                    Kategoriler
                </a>
            </h4>

            <div class="block_content panel-body" id="listpage_content">
                <ul class="tree list-unstyled">
                    <ul class="filter-middle">
                        {% for item in categories %}
                            <li>
                            <a href="{% change_parameter_url "c" item.slug %}"
                               title="{{ item.name }}">{{ item.name }}</a>
                            {% if show_count %}<span>({{ item.count }})</span>{% endif %}
                        {% endfor %}
                    </ul>
                </ul>
            </div>
</div>