shop/customer/urls.py
from django.core.urlresolvers import reverse_lazy
from django.conf.urls import patterns, url
from shop.customer.forms import PasswordResetForm

urlpatterns = patterns('',
                       url(r'^addresses/?$', 'shop.customer.views.user.customer_address', name="shop_customer_address"),
                       url(r'^addresses/add/?$', 'shop.customer.views.user.customer_address_modify', name="shop_customer_address_add"),
                       url(r'^addresses/([0-9]+)$', 'shop.customer.views.user.customer_address_modify', name="shop_customer_address_edit"),
                       url(r'^orders/?$', 'shop.customer.views.user.orders', name="shop_customer_orders"),
                       url(r'^profile/?$', 'shop.customer.views.user.profile', name="shop_customer_profile"),
                       url(r'^basket-action/?$', 'shop.customer.views.order.basket_action', name="shop_customer_basket"),
                       url(r'^basket/?$', 'shop.customer.views.order.basket_page', name="shop_customer_basket_page"),
                       url(r'^order/shipment$', 'shop.customer.views.order.order_shipment', name="shop_order_shipment"),
                       url(r'^order/address', 'shop.customer.views.order.order_address', name="shop_order_address"),
                       url(r'^order/payment', 'shop.customer.views.order.order_payment', name="shop_order_payment"),
                       url(r'^order/([0-9A-Za-z]+)', 'shop.customer.views.order.order_page', name="shop_customer_order"),
                       url(r'^logout/?$', 'shop.customer.views.membership.logout', name="shop_customer_logout"),
                       url(r'^login/?$', 'shop.customer.views.membership.login', name="shop_customer_login"),
                       url(r'^register/?$', 'shop.customer.views.membership.register', name="shop_customer_register"),
                       url(r'^password/reset/?$', 'shop.customer.views.membership.password_reset', {'password_reset_form': PasswordResetForm, 'post_reset_redirect': reverse_lazy('customer_password_reset_done'), 'template_name': 'customer/registration/password_reset_form.html'}, name="password_reset"),
                       url(r'^password/reset/done/?$', 'django.contrib.auth.views.password_reset_done', {'template_name': 'customer/registration/password_reset_done.html'}, name="customer_password_reset_done"),
                       url(r'^password/reset/(?P<uidb64>[0-9A-Za-z]+)/(?P<token>.+)/?$', 'shop.customer.views.membership.password_reset_confirm', {'template_name': 'customer/registration/password_reset_confirm.html', 'post_reset_redirect': reverse_lazy('customer_password_reset_complete')}, name="password_reset_confirm"),
                       url(r'^password/reset/complete/?$', 'django.contrib.auth.views.password_reset_complete', {'template_name': 'customer/registration/password_reset_complete.html'}, name="customer_password_reset_complete")
)

urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.views.decorators.cache import cache_page
from shop.sitemap import sitemaps
from django.contrib.sitemaps import views as sitemap_views

admin.autodiscover()

urlpatterns = patterns('',
       url(r'^', include("shop.urls", app_name='shop')),
       url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
       (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT, 'show_indexes': True}),
       url(r'^sitemap\.xml$', cache_page(86400)(sitemap_views.index), {'sitemaps': sitemaps, 'sitemap_url_name': 'sitemaps'}),
       url(r'^sitemap-(?P<section>.+)\.xml.gz$', cache_page(86400)(sitemap_views.sitemap), {'sitemaps': sitemaps}, name='sitemaps'),
       url(r'^doc/', include('django.contrib.admindocs.urls'), name="admin_docs"),
       url(r'^tinymce/', include('tinymce.urls')),
       url(r'^administratorPage/filebrowser/', include("filebrowser.urls")),
       url(r'^admin_tools/', include("admin_tools.urls"), name="django_admin_tools_url"),
       url(r'^administratorPage/', include(admin.site.urls), name="django_admin_url"),
)

handler404 = 'shop.views.handler404'
handler500 = 'shop.views.handler500'
handler403 = 'shop.views.handler403'
handler400 = 'shop.views.handler400'

shop/customer/forms.py
# coding: utf-8
from captcha.fields import ReCaptchaField
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.models import get_current_site
from django.forms.util import ErrorList
from django.template import loader
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import ugettext_lazy as _
from shop.customer.models import CustomerAddress
from shop.models import City, Ilce


class LoginForm(forms.Form):
    email = forms.CharField(max_length=100, label=_(u'Email'))
    password = forms.CharField(widget=forms.PasswordInput(), label=_(u'Password'))
    remember_me = forms.BooleanField(required=False, label=_(u'Remember me'))

    def __init__(self, *args, **kwargs):
        captcha = kwargs.pop('captcha', False)
        super(LoginForm, self).__init__(*args, **kwargs)
        if captcha:
            self.fields['captcha'] = ReCaptchaField()


INVOICE_TYPE_CHOICES = (('personal', _('personal')), ('company', _('company')))


class CustomerAddressForm(forms.ModelForm):
    invoice_type = forms.ChoiceField(label=_('invoice type'), widget=forms.RadioSelect, choices=INVOICE_TYPE_CHOICES,
                                     initial='personal')
    city = forms.ModelChoiceField(label=_('city'), queryset=City.objects.filter(country_id=1))

    class Meta:
        fields = (
            'address_name', 'first_name', 'last_name', 'address', 'postcode', 'land_line', 'cell_phone', 'city',
            'invoice_type', 'identity_number', 'tax_authority', 'tax_no')
        model = CustomerAddress

    def __init__(self, *args, **kwargs):
        super(CustomerAddressForm, self).__init__(*args, **kwargs)
        self.fields.keyOrder = [
            'address_name', 'first_name', 'last_name', 'address', 'postcode', 'land_line', 'cell_phone',
            'city', 'invoice_type', 'identity_number', 'tax_authority', 'tax_no']

        if kwargs.get('instance'):
            if len(args) > 0 and args[0].get('city'):
                city_id = args[0].get('city')
                self.fields['ilce'] = forms.ModelChoiceField(label=_('ilçe'), queryset=Ilce.objects.filter(city_id=city_id),
                                                             initial=kwargs.get('instance').ilce_id)
            elif kwargs.get('instance').ilce is not None:
                ilce = kwargs.get('instance').ilce
                self.fields['ilce'] = forms.ModelChoiceField(queryset=Ilce.objects.filter(city_id=ilce.city_id),
                                                             initial=ilce)
                self.fields['city'].initial = ilce.city_id
            if "ilce" in self.fields:
                self.fields.keyOrder = [
                'address_name', 'first_name', 'last_name', 'address', 'postcode', 'land_line', 'cell_phone',
                'city', 'ilce', 'invoice_type', 'identity_number', 'tax_authority', 'tax_no']

    class Media:
        js = ('customer/js/modify_address.js',)

    def clean(self):
        invoice_type = self.cleaned_data.get('invoice_type')
        if invoice_type == 'personal':
            if not self.cleaned_data.get('identity_number'):
                self._errors["identity_number"] = self.error_class([_("This field is required.")])
            self.cleaned_data['invoice_type'] = None
            self.cleaned_data['tax_no'] = None
        elif invoice_type == 'company':
            if not self.cleaned_data.get('tax_no'):
                self._errors["tax_no"] = self.error_class([_("This field is required.")])
            if not self.cleaned_data.get('tax_authority'):
                self._errors["tax_authority"] = self.error_class([_("This field is required.")])
            self.cleaned_data['identity_number'] = None
        data = super(CustomerAddressForm, self).clean()
        return data

    def save(self, force_insert=False, force_update=False, commit=True):
        if self.data.get('ilce') is not None:
            self.instance.ilce_id = int(self.data.get('ilce'))
        return super(CustomerAddressForm, self).save(commit)


class RegisterForm(forms.Form):
    email = forms.EmailField(label=_(u'Email'))
    password1 = forms.CharField(widget=forms.PasswordInput(), label=_(u'Password'), min_length=5)
    password2 = forms.CharField(widget=forms.PasswordInput(), label=_(u'Password *(Again)'))
    first_name = forms.CharField(label=_(u'First name'))
    last_name = forms.CharField(label=_(u'Last name'), required=False)
    phone = forms.CharField(label=_(u'Phone number'), required=False)
    agreement = forms.BooleanField(required=True)

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if not password2:
            raise forms.ValidationError("Şifrenizi teyit etmemiz için iki kere girmeniz gerekiyor.")
        if password1 != password2:
            raise forms.ValidationError("Şifreleriniz eşleşmiyor")
        return password2


class ProfileUpdateForm(forms.Form):
    email = forms.EmailField(label=_(u'Email'), required=False, )
    old_password = forms.CharField(widget=forms.PasswordInput(), label=_(u'Old Password'), required=False)
    new_password = forms.CharField(widget=forms.PasswordInput(), label=_(u'New password'), required=False)
    first_name = forms.CharField(label=_(u'First name'))
    last_name = forms.CharField(label=_(u'Last name'), required=False)
    phone = forms.CharField(label=_(u'Phone number'), required=False)

    def __init__(self, user, data=None, files=None, auto_id='id_%s', prefix=None,
                 initial=None, error_class=ErrorList, label_suffix=None,
                 empty_permitted=False):
        if data:
            data = data.copy()
            data['email'] = user.email
        else:
            initial = {"email": user.email, "first_name": user.first_name, "last_name": user.last_name,
                       "phone": user.phone}
        super(ProfileUpdateForm, self).__init__(data, files, auto_id, prefix,
                                                initial, error_class, label_suffix,
                                                empty_permitted)
        self.user = user
        self.fields['email'].widget.attrs['disabled'] = 'disabled'

    def clean(self):
        cleaned_data = super(ProfileUpdateForm, self).clean()
        if "new_password" in cleaned_data and not cleaned_data.get("old_password"):
            raise forms.ValidationError(_("You need to enter your old password in order to update your password"))
        return cleaned_data

    def clean_old_password(self):
        old_pass = self.cleaned_data.get('old_password')
        if old_pass and not self.user.check_password(old_pass):
            raise forms.ValidationError(_("The password you entered is wrong."))
        return old_pass

    def save(self):
        customer = self.user
        customer.email = self.cleaned_data['email']
        customer.first_name = self.cleaned_data['first_name']
        customer.last_name = self.cleaned_data['last_name']
        customer.phone = self.cleaned_data['phone']
        if self.cleaned_data.get('new_password'):
            customer.set_password(self.cleaned_data.get('new_password'))
        customer.save()


class PasswordResetForm(forms.Form):
    email = forms.EmailField(label=_("Email"), max_length=254)

    def __init__(self, *args, **kwargs):
        captcha = kwargs.pop('captcha', False)
        super(PasswordResetForm, self).__init__(*args, **kwargs)
        if captcha:
            self.fields['captcha'] = ReCaptchaField()


    def set_captcha(self):
        self.fields['captcha'] = ReCaptchaField()

    def save(self, domain_override=None,
             subject_template_name='registration/password_reset_subject.txt',
             email_template_name='registration/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None):
        """
        Generates a one-use only link for resetting password and sends to the
        user.
        """
        from django.core.mail import send_mail

        email = self.cleaned_data["email"]
        active_users = get_user_model()._default_manager.filter(
            email__iexact=email, is_active=True)
        for user in active_users:
            # Make sure that no email is sent to a user that actually has
            # a password marked as unusable
            if not user.has_usable_password():
                continue
            if not domain_override:
                current_site = get_current_site(request)
                site_name = current_site.name
                domain = current_site.domain
            else:
                site_name = domain = domain_override
            c = {
                'email': user.email,
                'domain': domain,
                'site_name': site_name,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'user': user,
                'token': token_generator.make_token(user),
                'protocol': 'https' if use_https else 'http',
            }
            subject = loader.render_to_string(subject_template_name, c)
            # Email subject *must not* contain newlines
            subject = ''.join(subject.splitlines())
            email = loader.render_to_string(email_template_name, c)
            send_mail(subject, email, from_email, [user.email])

shop/api/views/order.py
from datetime import datetime
from django.core.exceptions import SuspiciousOperation
from django.http import HttpResponse
from django.template import Template, Context
from simit.models import Page
from shop.customer.models import CustomerAddress
from vehicle import query


def satis_sozlesmesi(request):
    basket = query.get_basket(customer=request.user)
    content = Page.objects.get(slug="satis-sozlesmesi_1")

    t = request.GET.get("payment_type")
    if t not in ['havale', 'kredi-karti']:
        raise SuspiciousOperation("?")

    invoice_addr = CustomerAddress.objects.get(customer=request.user, id=request.session.get('orderAddress')['invoice'])
    shipment_addr = CustomerAddress.objects.get(customer=request.user, id=request.session.get('orderAddress')['shipment'])
    ct = {
        "tarih": datetime.now(),
        "odeme_tip": t,
        "kullanici": request.user,
        "urunler": [{"isim": b['product'].name, "miktar": b["quantity"], "fiyat": b['total_price']} for b in
                  basket['basket']],
        "tutar": basket['final_price'],
        "teslim_adresi": shipment_addr,
        "fatura_adresi": invoice_addr,
    }

    return HttpResponse(Template(content.content).render(Context(ct)))

shop/customer/templates/shop/default/customer/account/address.html
{% extends "shop/"|add:SHOP_TEMPLATE|add:"/customer/account/base.html" %}
{% load shop_tags fb_versions %}

{% block page_content %}
    <h2>Adreslerim</h2>
    <form method="POST" action="">{% csrf_token %}
        {% if addresses %}
        <table class="basket">
            <tr>
                <th></th>
                <th>Adres</th>
                <th>Varsayılan Fatura Adresi</th>
                <th>Varsayılan Teslimat Adresi</th>
            </tr>
            {% for address in addresses %}
                <tr>
                    <td style="width:25px"><a href="{% url "shop_customer_address_edit" address.id %}">Düzenle</a></td>
                    <td class="name">{{ address.first_name }} {{ address.last_name }}<br>{{ address.address }} {{ address.city.name }} {{ address.postcode }}</td>
{#                    <td class="radio">#}
                    <td>
                        <input type="radio" name="invoice" value="{{ address.id }}" {% if request.user.default_invoice_address_id == address.id %} checked {% endif %}>
                    </td>
{#                    <td class="radio">#}
                    <td>
                        <input type="radio" name="shipment" value="{{ address.id }}" {% if request.user.default_shipment_address_id == address.id %} checked {% endif %}>
                    </td>
                </tr>
            {% endfor %}
        </table>
        {% else %}
            <br>
            <div>Henüz hiçbir adresiniz yok.</div>
            <br>
        {% endif %}
        <div class="buttons" style="clear:both">
            <a href="{% url "shop_customer_address_add" %}" class="button_blue1">Yeni Adres Ekle</a>
            {% if addresses %}<input type="submit" class="button_blue1 right" value="Varsayılan olarak Kaydet">{% endif %}
        </div>
        <div style="clear:both; height:10px"></div>
    </form>
{% endblock %}

shop/customer/templates/shop/default/customer/account/address_add.html
{% extends "shop/"|add:SHOP_TEMPLATE|add:"/customer/account/base.html" %}
{% block page_content %}
    <div class="LoginHead clearfix">
        <h1>{% if form.instance.pk %}Adres Düzenle ({{ form.instance.address_name }}){% else %}Yeni adres ekle{% endif %}</h1>
    </div>
    <div class="LoginConAdress">
        <form action="" method="post"
              {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>{% csrf_token %}
            {% for error in form.non_field_errors %}
                <div>{{ error }}</div>
            {% endfor %}
            {% if form.errors %}
                <div>Lütfen aşağıdaki hataları düzeltin</div>
            {% endif %}
            {% for field in form %}
                <div class="fieldWrapper" id="{{ field.name }}-field">
                    {% for error in field.errors %}
                        <div class="alert alert-error">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                    {{ field.label_tag }} {{ field }}
                </div>
            {% endfor %}
            <div style="padding:5px; width:300px; background:#eee">Burada bildirdiğiniz bilgilerin doğruluğunu kontrol etmiyoruz. Vergi yükümlülükleriniz ya da kanuni haklarınız (garanti gibi) için bilgileri doğru olarak girmenizi öneririz.</div>
            <input class="button_blue1 button_size3" type="submit" value="{% if form.instance.pk %}Düzenle{% else %}Ekle{% endif %}">
        </form>
    </div>
    <style>
        #id_invoice_type li {
            display: inline-block;
        }
    </style>
{% endblock %}
{% block javascript_end %}
    {{ form.media }}
{% endblock %}

shop/customer/templates/shop/default/customer/account/base.html
{% extends "shop/"|add:SHOP_TEMPLATE|add:"/base.html" %}
{% load shop_tags simit_tags %}
{% block content %}
    <div class="wrapper">
        <div style="width:190px; float:left" class="sidebar-menu">
            <ul>
                <li><a href="{% url "shop_customer_orders" %}">Siparişlerim</a></li>
                <li><a href="{% url "shop_customer_profile" %}">Profil</a></li>
                <li><a href="{% url "shop_customer_address" %}">Adreslerim</a></li>
                <!--li><a href="{% url "shop_modules_messaging_list" %}">Mesajlarım</a></li-->
                <!--li><a href="{% url "shop_modules_pricedropalert_list" %}">Takip ettiklerim</a></li-->
            </ul>
        </div>
        {% getmenu "KULLANICI_MENU" as topheader %}
        {% if topheader %}
            <div class="left nav_ust_bg">
                <div class="nav_txt">
                    <ul class="clearfix">
                        {% for menu in topheader %}
                            <li><a href="{{ menu.url }}" title="{{ menu.title }}">{{ menu.title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <br>
        {% endif %}
        <div class="account-container">
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
            {% block page_content %}
                My Page
            {% endblock %}
        </div>
        <div style="clear:both"></div>
    </div>
{% endblock %}
{% block javascript_end %}
    <script>
        $('.sidebar-menu li a').each(function () {
            if (document.location.pathname.indexOf($(this).attr('href')) > -1)
                $(this).parent('li').addClass('active-menu');
        })
    </script>
{% endblock %}

shop/customer/templates/shop/default/customer/account/orders.html
{% extends "shop/"|add:SHOP_TEMPLATE|add:"/customer/account/base.html" %}
{% load humanize %}

{% block page_content %}
    <h1>Siparişlerim</h1>
    {% if orders %}
        <table class="styled_table" style="width:100%">
        <th>Sipariş Numarası</th>
        <th>Sipariş Durumu</th>
        <th>Kargo Takip</th>
        <th>Fiyat</th>
        <th>Tarih</th>
        <th></th>
        {% for order in orders %}
           <tr>
                <td><a href="{{ order.get_absolute_url }}">{{ order.receipt_id }}</a></td>
                <td>{{ order.statutes.last }}</td>
                <td>{% if order.cargo_no %}<a href="http://www.suratkargo.com.tr/kargoweb/bireysel.aspx?no={{ order.cargo_no }}">{{ order.cargo_no }}</a>{% else %}Henüz kargo takip numarası girilmemiş{% endif %}</td>
                <!--td>{% if order.cargo_no %}{{ order.cargo_no }}{% else %}Henüz kargo takip numarası girilmemiş{% endif %}</td-->
                <td>{{ order.final_price|floatformat:2|intcomma }} TL</td>
                <td>{{ order.date_processed }}</td>
           </tr>
        {% endfor %}
        </table>
    {% else %}
        <br>
        Henüz hiçbir siparişiniz yok.
    {% endif %}
{% endblock %}

shop/customer/templates/shop/default/customer/account/profile.html
{% extends "shop/"|add:SHOP_TEMPLATE|add:"/customer/account/base.html" %}
{% load widget_tweaks %}

{% block page_content %}
    <h1>Kişisel Bilgilerim</h1>
    <form action="" method="post" {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>{% csrf_token %}
        {% for error in form.non_field_errors %}
            {{ error }}
        {% endfor %}
        {% for field in form %}
            <div class="fieldWrapper">
                {{ field.errors }}
                {{ field.label_tag }}
                {{ field }}
            </div>
        {% endfor %}
        <input class="button_blue1 button_size3" type="submit" value="Güncelle">
    </form>
{% endblock %}